[build]
  command = "corepack pnpm build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_SKEW_PROTECTION = "true"

[functions]
  external_node_modules = [
    "sharp",
    "@img/sharp-linux-x64",
    "@img/sharp-libvips-linux-x64",
  ]
  included_files = [
    "node_modules/@img/sharp-linux-x64/**",
    "node_modules/@img/sharp-libvips-linux-x64/**",
  ]

[functions."run-payload-jobs"]
  schedule = "* * * * *"
